db:
  image: mysql:5.7
  ports:
    - '3306'
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  volumes:
    - ./Autolab/docker/mysql:/etc/mysql/conf.d
    - ./db-data:/var/lib/mysql

tango:
  build: ./Tango
  command: sh start.sh
  ports:
    - '8600:8600'
  privileged: true
  volumes: 
  - ./Tango/config.py:/opt/TangoService/Tango/config.py
  - ./Tango/start.sh:/opt/TangoService/Tango/start.sh
  - ./Tango/vmms/ITCS-5152:/opt/TangoService/Tango/vmms/ITCS-5152
  - ./Tango/vmms/ITCS-4156:/opt/TangoService/Tango/vmms/ITCS-4156


web:
  build: ./Autolab
  env_file: .env
  links:
    - db
    - tango
  ports:
    - '80:80'
    - '443:443'
  volumes:
    - ./Autolab/courses:/home/app/webapp/courses
    - ./ssl:/etc/nginx/ssl
